### PR TITLE
split RPM installation into chunks ignoring dependencies

### PR DESCRIPTION
**Pull request by clelange**
@smuzaffar  This is probably not a perfect solution to address #1 , doing so also causes errors and one cannot be sure that the packages are properly installed, so take it as a suggestion. This is unfortunately currently blocking my workflow and any fix would be appreciated.
One would probably want to use `subprocess.Popen` as in https://github.com/cms-sw/cmspkg/blob/master/client/cmspkg.py#L39, but since default on lxplus is python 2.6.6 one actually gets the system python implementation of `getstatusoutput`, which then cannot cope with decoding the output.

Example error when installing with the code as in the PR:

```
Get:206 http://cmsrep.cern.ch cmssw/cms/slc6_amd64_gcc481 cms+gcc-toolfile+12.0-cms3-1-1.slc6_amd64_gcc481.rpm
Downloaded 6073MB of archives.
After unpacking 12585MB of additional disk space will be used.
Executing RPM (source /afs/cern.ch/user/c/clange/work/bootstrap/install/share/cms/cmspkg/V00-00-23/rpm_env.sh slc6_amd64_gcc481; rpm -Uvh -r /afs/cern.ch/user/c/clange/work/
bootstrap/install --force --prefix /afs/cern.ch/user/c/clange/work/bootstrap/install --ignoreos --ignorearch --oldpackage --nodeps )...
cd /afs/cern.ch/user/c/clange/work/bootstrap/install/slc6_amd64_gcc481/var/cmspkg/rpms && source /afs/cern.ch/user/c/clange/work/bootstrap/install/share/cms/cmspkg/V00-00-23
/rpm_env.sh slc6_amd64_gcc481; rpm -Uvh -r /afs/cern.ch/user/c/clange/work/bootstrap/install --force --prefix /afs/cern.ch/user/c/clange/work/bootstrap/install --ignoreos --
ignorearch --oldpackage --nodeps  cms+cmssw+CMSSW_7_1_28-1-1.slc6_amd64_gcc481.rpm external+protobuf+2.4.1-1-1.slc6_amd64_gcc481.rpm cms+icc-gcc-toolfile+2.0-cms3-1-1.slc6_a
md64_gcc481.rpm external+libjpg+8b-1-1.slc6_amd64_gcc481.rpm external+xrootd+3.2.4-cms2-1-1.slc6_amd64_gcc481.rpm
Preparing...                ########################################### [100%]
   1:external+xrootd+3.2.4-c########################################### [ 20%]
   2:external+libjpg+8b     ########################################### [ 40%]
   3:cms+icc-gcc-toolfile+2.########################################### [ 60%]
   4:external+protobuf+2.4.1########################################### [ 80%]
   5:cms+cmssw+CMSSW_7_1_28 ########################################### [100%]
Can't locate Cache/CacheUtilities.pm in @INC (@INC contains: /afs/cern.ch/user/c/clange/work/bootstrap/install/slc6_amd64_gcc481/lcg/SCRAMV1/V2_2_6_pre4/src /usr/local/lib64
/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./config/SCRAM/projectAreaRename.pl line 3.
BEGIN failed--compilation aborted at ./config/SCRAM/projectAreaRename.pl line 3.
Can't locate Cache/CacheUtilities.pm in @INC (@INC contains: /afs/cern.ch/user/c/clange/work/bootstrap/install/slc6_amd64_gcc481/lcg/SCRAMV1/V2_2_6_pre4/src /usr/local/lib64
/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./config/SCRAM/projectAreaRename.pl line 3.
BEGIN failed--compilation aborted at ./config/SCRAM/projectAreaRename.pl line 3.
find: "/afs/cern.ch/user/c/clange/work/bootstrap/install/slc6_amd64_gcc481/external/file/5.13/bin/file": file or directory not found
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @clelange . I think the real issue is the disk space. We have seen this error when we were installing releases on AFS. How much diskquota you have 
```fs lq /afs/cern.ch/user/c/clange```
Do you get the same error if you install it on /tmp/clange (with more than 30GB space)?

**Comment by clelange** [comment]
I tried installing in both an lxplus `/tmp/clange/` as well as to my work area, which has more than 35 GB of space available:
```
Volume Name                    Quota       Used %Used   Partition
work.clange                104857600   64559100   62%         53%
```


I then tried to use subprocess instead of the sys module, changing L671 ff. this way:
```
#Install the nwly downloaded packages(s)
    import subprocess
    print cmd
    p = subprocess.Popen([cmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = p.communicate()
    if p.returncode>0:
        print "Something went wrong"
        print out
        print err
        exit(1)
    self.update_rpm_cache(True)
```

and this is the output:

```
Downloading indirect dependencies....
0 upgraded, 1 newly installed, 0 removed and 0 not upgraded
Get:206 http://cmsrep.cern.ch cmssw/cms/slc6_amd64_gcc481 cms+gcc-toolfile+12.0-cms3-1-1.slc6_amd64_gcc481.rpm
Downloaded 6073MB of archives.
After unpacking 12585MB of additional disk space will be used.
Executing RPM (source /afs/cern.ch/work/c/clange/bootstrap/install/share/cms/cmspkg/V00-00-23/rpm_env.sh slc6_amd64_gcc481; rpm -Uvh -r /afs/cern.ch/w
ork/c/clange/bootstrap/install --force --prefix /afs/cern.ch/work/c/clange/bootstrap/install --ignoreos --ignorearch --oldpackage )...
cd /afs/cern.ch/work/c/clange/bootstrap/install/slc6_amd64_gcc481/var/cmspkg/rpms && source /afs/cern.ch/work/c/clange/bootstrap/install/share/cms/cms
pkg/V00-00-23/rpm_env.sh slc6_amd64_gcc481; rpm -Uvh -r /afs/cern.ch/work/c/clange/bootstrap/install --force --prefix /afs/cern.ch/work/c/clange/boots
trap/install --ignoreos --ignorearch --oldpackage  cms+cmssw+CMSSW_7_1_28-1-1.slc6_amd64_gcc481.rpm  external+protobuf+2.4.1-1-1.slc6_amd64_gcc481.rpm
  cms+icc-gcc-toolfile+2.0-cms3-1-1.slc6_amd64_gcc481.rpm  external+libjpg+8b-1-1.slc6_amd64_gcc481.rpm  external+xrootd+3.2.4-cms2-1-1.slc6_amd64_gcc
481.rpm  external+sherpa+2.2.2-ddibom-1-1.slc6_amd64_gcc481.rpm  cms+data-RecoMuon-MuonIdentification+V01-12-01-1-1.slc6_amd64_gcc481.rpm  external+py
2-zsi+2.0-cms2-1-1.slc6_amd64_gcc481.rpm  lcg+roofit+5.34.18-cms4-1-1.slc6_amd64_gcc481.rpm  external+charybdis+1.003-ddibom5-1-1.slc6_amd64_gcc481.rp
m  cms+data-Geometry-TrackerRecoData+V01-04-05-1-1.slc6_amd64_gcc481.rpm  external+libtiff+3.9.4-1-1.slc6_amd64_gcc481.rpm  external+systemtools+19-cm
s-1-1.slc6_amd64_gcc481.rpm  external+py2-lint+0.25.1-cms2-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-CaloEventSetup+V03-11-02-1-1.slc6_amd64_gcc481
.rpm  external+ktjet+1.06-cms3-1-1.slc6_amd64_gcc481.rpm  external+py2-pyxml+0.8.4-cms2-1-1.slc6_amd64_gcc481.rpm  external+glibc+2.12-2-1-1.slc6_amd6
4_gcc481.rpm  external+openloops+1.3.1-1-1.slc6_amd64_gcc481.rpm  external+sqlite+3.7.17-1-1.slc6_amd64_gcc481.rpm  cms+data-FastSimulation-PileUpProd
ucer+V04-05-18-cms-1-1.slc6_amd64_gcc481.rpm  external+geant4-G4NEUTRONXS+1.4-1-1.slc6_amd64_gcc481.rpm  cms+data-CalibCalorimetry-CaloMiscalibTools+V
01-00-00-1-1.slc6_amd64_gcc481.rpm  cms+gcc-toolfile+12.0-cms3-1-1.slc6_amd64_gcc481.rpm  cms+data-FastSimulation-MaterialEffects+V04-02-08-1-1.slc6_a
md64_gcc481.rpm  external+dpm+1.8.0.1-1-1.slc6_amd64_gcc481.rpm  external+sigcpp+2.2.10-cms4-1-1.slc6_amd64_gcc481.rpm  external+valgrind+3.9.0-cms4-1
-1.slc6_amd64_gcc481.rpm  external+py2-numpy+1.6.1-cms2-1-1.slc6_amd64_gcc481.rpm  external+py2-matplotlib+1.2.1-cms2-1-1.slc6_amd64_gcc481.rpm  exter
nal+py2-sqlalchemy+0.8.2-cms3-1-1.slc6_amd64_gcc481.rpm  external+gdb+7.7-cms4-1-1.slc6_amd64_gcc481.rpm  external+photospp+3.56-1-1.slc6_amd64_gcc481
.rpm  external+google-perftools+1.6-1-1.slc6_amd64_gcc481.rpm  external+dmtcp+2.0-2212-1-1.slc6_amd64_gcc481.rpm  lcg+root+5.34.18-cms5-1-1.slc6_amd64
_gcc481.rpm  cms+cms-git-tools+140602.0-1-1.slc6_amd64_gcc481.rpm  external+rivet+1.8.2-cms8-1-1.slc6_amd64_gcc481.rpm  external+libpng+1.6.0-cms-1-1.
slc6_amd64_gcc481.rpm  external+sloccount+2.26-cms4-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-ForwardSimData+V02-02-00-1-1.slc6_amd64_gcc481.rpm  e
xternal+py2-pygithub+1.23.0-cms-1-1.slc6_amd64_gcc481.rpm  external+openssl+0.9.8e__1.0.1-cms-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-MuonSimData
+V01-03-00-1-1.slc6_amd64_gcc481.rpm  external+qt+4.8.1-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-MTCCTrackerCommonData+V01-01-00-1-1.slc6_amd64_gc
c481.rpm  cms+data-Geometry-FP420CommonData+V00-06-00-1-1.slc6_amd64_gcc481.rpm  cms+ccache-gcc-toolfile+1.0-1-1.slc6_amd64_gcc481.rpm  external+rivet
2+2.0.0-cms6-1-1.slc6_amd64_gcc481.rpm  external+expat+2.0.1-1-1.slc6_amd64_gcc481.rpm  external+py2-scipy+0.8.0-cms2-1-1.slc6_amd64_gcc481.rpm  exter
nal+curl+7.28.0-cms-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-TrackerSimData+V01-02-05-1-1.slc6_amd64_gcc481.rpm  external+llvm+3.4-cms2-1-1.slc6_a
md64_gcc481.rpm  external+openldap+2.4.34-cms-1-1.slc6_amd64_gcc481.rpm  cms+data-SimG4CMS-Calo+V03-00-00-cms2-1-1.slc6_amd64_gcc481.rpm  external+ncu
rses+5.9-1-1.slc6_amd64_gcc481.rpm  external+gnuplot+4.6.1-1-1.slc6_amd64_gcc481.rpm  cms+cmsswdata+27-ddibom5-1-1.slc6_amd64_gcc481.rpm  external+pro
fessor+1.0.0-cms19-1-1.slc6_amd64_gcc481.rpm  external+cmake+2.8.10-cms-1-1.slc6_amd64_gcc481.rpm  cms+data-SimG4CMS-Forward+V02-03-18-1-1.slc6_amd64_
gcc481.rpm  cms+data-Geometry-HcalTestBeamData+V01-08-00-1-1.slc6_amd64_gcc481.rpm  external+pcre+7.9__8.33-1-1.slc6_amd64_gcc481.rpm  external+graphv
iz+2.16.1-cms-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-RPCGeometryBuilder+V01-04-00-1-1.slc6_amd64_gcc481.rpm  external+patchelf+0.8-1-1.slc6_amd6
4_gcc481.rpm  external+hepmc+2.06.07-cms4-1-1.slc6_amd64_gcc481.rpm  external+blackhat+0.9.9-cms3-1-1.slc6_amd64_gcc481.rpm  lcg+SCRAMV1+V2_2_6_pre4-1
-1.slc6_amd64_gcc481.rpm  external+file+5.13-1-1.slc6_amd64_gcc481.rpm  external+dcap+2.47.8-cms2-1-1.slc6_amd64_gcc481.rpm  cms+data-RecoJets-JetProd
ucers+V05-10-12-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-FP420SimData+V00-06-00-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-HcalSimData+V01-03-00
-1-1.slc6_amd64_gcc481.rpm  cms+dbs-client+DBS_2_1_9-cms2-1-1.slc6_amd64_gcc481.rpm  external+boost+1.51.0-cms2-1-1.slc6_amd64_gcc481.rpm  external+db
4+4.4.20-1-1.slc6_amd64_gcc481.rpm  external+cascade+2.2.04-ddibom5-1-1.slc6_amd64_gcc481.rpm  external+geant4data+1.0-cms-1-1.slc6_amd64_gcc481.rpm
cms+distcc-gcc-toolfile+2.0-cms5-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-EcalCommonData+V05-05-00-1-1.slc6_amd64_gcc481.rpm  external+cvs2git+541
9-cms2-1-1.slc6_amd64_gcc481.rpm  external+py2-ipython+0.10-cms2-1-1.slc6_amd64_gcc481.rpm  cms+das_client+v02.17.04-1-1.slc6_amd64_gcc481.rpm  cms+cm
ssw-tool-conf+31.0-ddibom13-1-1.slc6_amd64_gcc481.rpm  external+evtgenlhc+9.1-cms3-1-1.slc6_amd64_gcc481.rpm  external+cgal+4.2-cms6-1-1.slc6_amd64_gc
c481.rpm  cms+data-GeneratorInterface-EvtGenInterface+V02-00-08-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-HcalCommonData+V01-05-00-1-1.slc6_amd64_g
cc481.rpm  external+mcdb+1.0.2-cms-1-1.slc6_amd64_gcc481.rpm  external+libungif+4.1.4-1-1.slc6_amd64_gcc481.rpm  external+tbb+42_20131118oss-1-1.slc6_
amd64_gcc481.rpm  cms+data-Configuration-Generator+V01-00-01-1-1.slc6_amd64_gcc481.rpm  external+geant4-G4ABLA+3.0-1-1.slc6_amd64_gcc481.rpm  external
+geant4-parfullcms+2014.01.27-ddibom2-1-1.slc6_amd64_gcc481.rpm  external+icc+composer_xe_2013.2.146-1-1.slc6_amd64_gcc481.rpm  external+heppdt+3.03.0
0-1-1.slc6_amd64_gcc481.rpm  external+py2-pycurl+7.19.0-cms2-1-1.slc6_amd64_gcc481.rpm  external+py2-pytz+2007d-cms2-1-1.slc6_amd64_gcc481.rpm  cms+da
ta-CondFormats-JetMETObjects+V01-00-01-1-1.slc6_amd64_gcc481.rpm  external+swig+2.0.12-1-1.slc6_amd64_gcc481.rpm  cms+data-RecoParticleFlow-PFProducer
+V15-00-00-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-TwentyFivePercentTrackerCommonData+V00-01-00-1-1.slc6_amd64_gcc481.rpm  external+lapack+3.3.1-
cms-1-1.slc6_amd64_gcc481.rpm  external+xz+5.0.3__5.1.2alpha-cms5-1-1.slc6_amd64_gcc481.rpm  external+libhepml+0.2.1-1-1.slc6_amd64_gcc481.rpm  extern
al+lhapdf+6.1.6-ddibom-1-1.slc6_amd64_gcc481.rpm  external+py2-cjson+1.0.5-cms2-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-DTGeometryBuilder+V00-05-
00-1-1.slc6_amd64_gcc481.rpm  external+millepede+V04-00-02-1-1.slc6_amd64_gcc481.rpm  cms+data-GeneratorInterface-ReggeGribovPartonMCInterface+V00-00-
02-1-1.slc6_amd64_gcc481.rpm  external+distcc+3.2rc1-cms3-1-1.slc6_amd64_gcc481.rpm  external+pyminuit2+0.0.1-cms19-1-1.slc6_amd64_gcc481.rpm  externa
l+geant4-G4NDL+4.4-1-1.slc6_amd64_gcc481.rpm  external+gcc+4.8.1-1-1.slc6_amd64_gcc481.rpm  external+zlib+1.2.8-1-1.slc6_amd64_gcc481.rpm  external+si
p+4.11.2-cms2-1-1.slc6_amd64_gcc481.rpm  external+cuda+1.0-1-1.slc6_amd64_gcc481.rpm  cms+data-DQM-PhysicsHWW+V01-00-00-1-1.slc6_amd64_gcc481.rpm  cms
+llvm-gcc-toolfile+13.0-cms9-1-1.slc6_amd64_gcc481.rpm  cms+data-MagneticField-Interpolation+V00-05-00-1-1.slc6_amd64_gcc481.rpm  external+python+2.7.
6-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-ForwardCommonData+V01-05-00-1-1.slc6_amd64_gcc481.rpm  external+frontier_client+2.8.20-1-1.slc6_amd64_g
cc481.rpm  external+tauolapp+1.1.4-ddibom7-1-1.slc6_amd64_gcc481.rpm  external+clhep+2.1.4.1-cms-1-1.slc6_amd64_gcc481.rpm  external+fastjet+3.0.3-cms
2-1-1.slc6_amd64_gcc481.rpm  external+geant4+10.00.p02-ddibom2-1-1.slc6_amd64_gcc481.rpm  cms+data-CalibTracker-SiPixelESProducers+V02-00-00-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-TrackerCommonData+V01-09-05-1-1.slc6_amd64_gcc481.rpm  external+tauola+27.121.5-1-1.slc6_amd64_gcc481.rpm  externa
l+bz2lib+1.0.5-1-1.slc6_amd64_gcc481.rpm  external+fasthadd+1.1-cms3-1-1.slc6_amd64_gcc481.rpm  cms+vdt+v0.3.2-cms-1-1.slc6_amd64_gcc481.rpm  cms+data
-RecoParticleFlow-PFTracking+V13-01-00-1-1.slc6_amd64_gcc481.rpm  external+opencl+1.1-1-1.slc6_amd64_gcc481.rpm  external+mctester+1.25.0a-cms19-1-1.s
lc6_amd64_gcc481.rpm  external+pyqt+4.8.1-cms2-1-1.slc6_amd64_gcc481.rpm  external+freetype+2.4.7-1-1.slc6_amd64_gcc481.rpm  external+igprof+5.9.10-1-
1.slc6_amd64_gcc481.rpm  cms+data-Geometry-CMSCommonData+V01-09-00-1-1.slc6_amd64_gcc481.rpm  external+pacparser+1.3.5-1-1.slc6_amd64_gcc481.rpm  exte
rnal+geant4-G4EMLOW+6.35-1-1.slc6_amd64_gcc481.rpm  external+gsl+1.10-1-1.slc6_amd64_gcc481.rpm  external+gccxml+0.9.0-20140124-0-1-1.slc6_amd64_gcc48
1.rpm  external+jimmy+4.2-ddibom5-1-1.slc6_amd64_gcc481.rpm  cms+data-Validation-Geometry+V00-07-00-1-1.slc6_amd64_gcc481.rpm  external+glimpse+4.18.5
-1-1.slc6_amd64_gcc481.rpm  cms+data-RecoLocalCalo-EcalDeadChannelRecoveryAlgos+V01-00-00-1-1.slc6_amd64_gcc481.rpm  external+castor+2.1.13.9-cms-1-1.
slc6_amd64_gcc481.rpm  cms+oracle-env+29-cms-1-1.slc6_amd64_gcc481.rpm  external+readline+6.2-cms-1-1.slc6_amd64_gcc481.rpm  external+opencl-cpp+1.1-1
-1.slc6_amd64_gcc481.rpm  external+xerces-c+2.8.0-1-1.slc6_amd64_gcc481.rpm  external+python-ldap+2.4.10-cms2-1-1.slc6_amd64_gcc481.rpm  external+gmak
e+3.81-1-1.slc6_amd64_gcc481.rpm  cms+data-DetectorDescription-Schema+V02-02-01-1-1.slc6_amd64_gcc481.rpm  external+libxml2+2.7.7-1-1.slc6_amd64_gcc48
1.rpm  external+cython+0.19.1-cms-1-1.slc6_amd64_gcc481.rpm  external+py2-python-dateutil+1.1-cms2-1-1.slc6_amd64_gcc481.rpm  external+lcov+1.9-1-1.sl
c6_amd64_gcc481.rpm  external+thepeg+1.9.2p1-ddibom5-1-1.slc6_amd64_gcc481.rpm  external+yoda+1.0.4-cms-1-1.slc6_amd64_gcc481.rpm  external+fftjet+1.5
.0-1-1.slc6_amd64_gcc481.rpm  external+photos+215.5-1-1.slc6_amd64_gcc481.rpm  external+fastjet-contrib+1.009-cms3-1-1.slc6_amd64_gcc481.rpm  external
+pythia8+226-1-1.slc6_amd64_gcc481.rpm  external+fftw3+3.3.2-1-1.slc6_amd64_gcc481.rpm  cms+data-RecoEgamma-ElectronIdentification+V01-00-01-1-1.slc6_
amd64_gcc481.rpm  external+cppunit+1.12.1-1-1.slc6_amd64_gcc481.rpm  external+classlib+3.1.3-cms5-1-1.slc6_amd64_gcc481.rpm  external+git+1.8.3.1-ddib
om-1-1.slc6_amd64_gcc481.rpm  cms+data-L1Trigger-RPCTrigger+V00-15-00-1-1.slc6_amd64_gcc481.rpm  external+geant4-G4RadioactiveDecay+4.0-1-1.slc6_amd64
_gcc481.rpm  external+herwig+6.521-ddibom5-1-1.slc6_amd64_gcc481.rpm  external+evtgen+1.3.0-ddibom7-1-1.slc6_amd64_gcc481.rpm  external+tkonlinesw+2.7
.0-cms2-1-1.slc6_amd64_gcc481.rpm  external+hector+1_3_4-cms19-1-1.slc6_amd64_gcc481.rpm  cms+coral+CORAL_2_3_21-ddibom4-1-1.slc6_amd64_gcc481.rpm  cm
s+coral-tool-conf+2.1-ddibom3-1-1.slc6_amd64_gcc481.rpm  cms+data-RecoParticleFlow-PFBlockProducer+V02-04-02-1-1.slc6_amd64_gcc481.rpm  external+doxyg
en+1.8.5-cms5-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-EcalTestBeam+V00-09-09-1-1.slc6_amd64_gcc481.rpm  external+jemalloc+3.5.0-1-1.slc6_amd64_gc
c481.rpm  external+geant4-G4SAIDDATA+1.1-cms-1-1.slc6_amd64_gcc481.rpm  external+py2-networkx+1.8.1-cms-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-C
SCGeometryBuilder+V01-08-00-1-1.slc6_amd64_gcc481.rpm  external+ccache+3.1.8-1-1.slc6_amd64_gcc481.rpm  external+geant4-G4PhotonEvaporation+3.0-1-1.sl
c6_amd64_gcc481.rpm  external+meschach+1.2.pCMS1-1-1.slc6_amd64_gcc481.rpm  external+pythia6+426-1-1.slc6_amd64_gcc481.rpm  external+herwigpp+2.7.1-dd
ibom5-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-MuonCommonData+V01-06-00-1-1.slc6_amd64_gcc481.rpm  external+autotools+1.1-cms-1-1.slc6_amd64_gcc48
1.rpm  external+libuuid+2.22.2-1-1.slc6_amd64_gcc481.rpm  external+toprex+4.23-1-1.slc6_amd64_gcc481.rpm  cms+data-Geometry-EcalSimData+V01-02-00-1-1.
slc6_amd64_gcc481.rpm  external+fakesystem+1.0-1-1.slc6_amd64_gcc481.rpm  external+oracle+11.2.0.3.0__10.2.0.4.0-1-1.slc6_amd64_gcc481.rpm  external+g
dbm+1.10-1-1.slc6_amd64_gcc481.rpm  cms+data-Fireworks-Geometry+V07-05-00-1-1.slc6_amd64_gcc481.rpm  external+py2-cx-oracle+5.1-cms3-1-1.slc6_amd64_gc
c481.rpm  external+alpgen+214-cms-1-1.slc6_amd64_gcc481.rpm  external+yaml-cpp+0.5.1-cms-1-1.slc6_amd64_gcc481.rpm  external+qd+2.3.13-1-1.slc6_amd64_
gcc481.rpm
Traceback (most recent call last):
  File "/afs/cern.ch/work/c/clange/bootstrap/install/share/cms/cmspkg/V00-00-23/cmspkg.py", line 1168, in <module>
    process(args, opts, cache_dir)
  File "/afs/cern.ch/work/c/clange/bootstrap/install/share/cms/cmspkg/V00-00-23/cmspkg.py", line 1061, in process
    repo.install(pkg, reinstall=opts.reinstall, force=opts.force)
  File "/afs/cern.ch/work/c/clange/bootstrap/install/share/cms/cmspkg/V00-00-23/cmspkg.py", line 674, in install
    p = subprocess.Popen([cmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 36] File name too long
```

Looking around how one could solve this, I thought one could use a wildcard for the `.rpm` files or maybe use `yum` instead of `rpm` to get the dependencies installed automatically instead of listing them explicitly. Maybe you have a smart way of splitting the installation of the packages such that the ones others depend on get installed first in a separate step?

**Comment by clelange** [comment]
Please see #1 to reproduce this on lxplus.

**Comment by smuzaffar** [comment]
I actually ran the exact same commands on lxplus and was able to install it under /afs/cern.ch/work/m/muzaffar/public/cmpk (where I had 43GB free disk).
```
wget cmsrep.cern.ch/cmssw/repos/bootstrap.sh
sh ./bootstrap.sh -r cms -a slc6_amd64_gcc481 -p `pwd` setup
./common/cmspkg -a slc6_amd64_gcc481 install -y cms+cmssw+CMSSW_7_1_28
....
.....
sh -c strings /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_28/test/slc6_amd64_gcc481/writeTestTagDB 2>&1 | grep 'slc6_amd64_gcc481/external/glibc' 2>&1 >/dev/null && /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/external/patchelf/0.8/bin/patchelf --set-interpreter /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/external/glibc/2.12-2/lib64/ld.so /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_28/test/slc6_amd64_gcc481/writeTestTagDB || true 
sh -c strings /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_28/test/slc6_amd64_gcc481/xmlToolsRun 2>&1 | grep 'slc6_amd64_gcc481/external/glibc' 2>&1 >/dev/null && /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/external/patchelf/0.8/bin/patchelf --set-interpreter /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/external/glibc/2.12-2/lib64/ld.so /afs/cern.ch/work/m/muzaffar/public/cmpk/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_28/test/slc6_amd64_gcc481/xmlToolsRun || true 
muzaffar@lxplus071.cern.ch>echo $?
0
```

**Comment by clelange** [comment]
OK, I finally also managed to get it to work as well. It really seems to have been a disk space issue. A few comments before closing this:

- the bootstrap script fails on eos
- it would be nice to get an error message why a command fails
- since there is explicit grepping, a safety measure would be to check that `LC_ALL` is either not set or if so set to `en_US.UTF-8`

Apart from that I'm very happy with this script. Thanks for your help, @smuzaffar !

**Comment by smuzaffar** [comment]
thanks for your feedback. YEs I also noticed that in some situations script does not report the error. I will try to improve the error reporting.

**Pull request closed without merging**
